SETTINGS:
  DIRECTORY: '/home/GRAMES.POLYMTL.CA/u114716/coursework/brain-hack/data/spine-generic/sub-amu01' 
  PROJECT_NAME: 'INRs'
  GROUP_NAME: 'spine-generic'
  RUN_NAME: 'FF_MAP=512_FFS=4_NUML=8_HID=1024_LR=0.0002_T2w_0.884_4.88_GT_0.5_mask-min'
  GPU_DEVICE: 0
  NUM_WORKERS: 16

DATASET:
  SUBJECT_ID: 'sub-amu01' 
  SESSION_ID: '' 
  VIEW1_LABEL: 'T2w_0.8x0.8x4.0'
  VIEW2_LABEL: 'T2w_4.0x0.8x0.8' 
  GT_LABEL: 'T2w_0.5'
  GT_MASK_LABEL: 'T2w_0.5x0.5x0.5_mask_min' 

TRAINING:
  SEED: 12
  BATCH_SIZE: 1024
  LR: 0.0004
  EPOCHS: 50
  OPTIM: 'Adam'
  SHUFFELING: True
  LOSS: 'MSELoss' # "L1LOSS"

MODEL:
  # GENERAL
  NUM_LAYERS: 4
  HIDDEN_CHANNELS: 1024
  DROPOUT: 0.0
  # ENCODINGS
  USE_SIREN: True
  USE_WIRE_REAL: False
  USE_FF: False

FOURIER:
  MAPPING_SIZE: 512 # each per cos/sine
  FF_SCALE: 4.0
  FF_FACTOR: 1.0
